'use client';
import { Activity, Clock3, Target, Users, Zap, Star } from 'lucide-react';
import type { ModuleDocument } from '@/lib/types';
import { useMemo, useState } from 'react';
import { motion } from 'framer-motion';
export function Analytics() { const [range, setRange] = useState('30d'); const points = useMemo(() => [68, 72, 70, 76, 81, 79, 86, 84, 91, 88, 94, 96], [range]); return <section className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.8fr]"><div className="rounded-3xl border bg-white p-6"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><h2 className="font-black">Learner analytics</h2><p className="text-xs text-slate-400">Simulated product telemetry for portfolio demonstration.</p></div><select className="input max-w-32" value={range} onChange={e => setRange(e.target.value)}><option value="7d">7 days</option><option value="30d">30 days</option><option value="90d">90 days</option></select></div><div className="mt-7 grid gap-3 sm:grid-cols-4"><Metric label="Active learners" value="2,418" change="+18.4%"/><Metric label="Completion" value="78.6%" change="+6.2%"/><Metric label="Avg. score" value="86%" change="+4.8%"/><Metric label="Time spent" value="14m 32s" change="+11.1%"/></div><div className="mt-7 rounded-2xl bg-slate-950 p-5"><div className="flex items-center justify-between text-xs text-slate-400"><span>Completion trend</span><span>Last {range}</span></div><div className="mt-6 flex h-40 items-end gap-2">{points.map((v, i) => <motion.div initial={{ height: 0 }} animate={{ height: `${v}%` }} transition={{ delay: i * .03 }} key={i} className="flex-1 rounded-t-lg bg-blue-500/80" title={`${v}%`}/>)}</div></div></div><div className="space-y-5"><div className="rounded-3xl border bg-white p-6"><div className="flex items-center gap-2"><Activity size={18} className="text-blue-600"/><h2 className="font-black">Drop-off points</h2></div><div className="mt-5 space-y-3">{[['Intro', '4%'], ['Scenario', '9%'], ['Knowledge check', '13%'], ['Final assessment', '7%']].map(([x, v]) => <div key={x}><div className="flex justify-between text-xs font-bold"><span>{x}</span><span>{v}</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-500" style={{ width: v }}/></div></div>)}</div></div><div className="rounded-3xl border bg-white p-6"><div className="text-xs font-black uppercase tracking-widest text-slate-400">Top learner signal</div><div className="mt-4 flex gap-3"><Star className="text-amber-500" fill="currentColor"/><div><div className="font-black">Scenario Simulator</div><p className="mt-1 text-xs leading-5 text-slate-500">Highest interaction rate and strongest completion correlation.</p></div></div></div></div></section>; }
function Metric({ label, value, change }: {
    label: string;
    value: string;
    change: string;
}) { return <div className="rounded-2xl bg-slate-50 p-4"><div className="text-2xl font-black">{value}</div><div className="mt-1 text-xs font-bold">{label}</div><div className="mt-2 text-[10px] font-black text-emerald-600">{change}</div></div>; }

