'use client';
import { Check, MessageSquare, Send, Users, X } from 'lucide-react';
import { useState } from 'react';
import { useModuleStore } from '@/store/module-store';
import { ChevronRight } from 'lucide-react';
import type { ModuleDocument } from '@/lib/types';
export function Collaboration() { const selected = useModuleStore(s => s.selectedBlockId); const doc = useModuleStore(s => s.document); const [comments, setComments] = useState([{ id: 1, name: 'Maya Chen', text: 'The scenario is strong. Add one more consequence to make the decision clearer.', time: '8m ago', resolved: false }, { id: 2, name: 'Omar Hassan', text: 'Can we simplify the intro before publishing?', time: '22m ago', resolved: true }]); const [text, setText] = useState(''); const [review, setReview] = useState(false); const add = () => { if (!text.trim())
    return; setComments(c => [{ id: Date.now(), name: 'You', text: text.trim(), time: 'now', resolved: false }, ...c]); setText(''); }; return <section className="mt-5 grid gap-5 lg:grid-cols-[1fr_.8fr]"><div className="rounded-3xl border bg-white p-6"><div className="flex items-center justify-between"><div><h2 className="font-black">Review & collaboration</h2><p className="text-xs text-slate-400">Inline feedback, reviewers and release handoff.</p></div><div className="flex -space-x-2"><Avatar text="MC"/><Avatar text="OH"/><Avatar text="IB"/></div></div><div className="mt-6 flex items-center gap-2 rounded-2xl bg-blue-50 p-4 text-xs font-semibold text-blue-800"><MessageSquare size={16}/>{selected ? `Commenting on selected block ${selected.slice(0, 6)}…` : 'Select a block in Builder to anchor a comment.'}</div><textarea className="input mt-4 min-h-24" placeholder="Leave review feedback…" value={text} onChange={e => setText(e.target.value)}/><button onClick={add} className="mt-2 inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-xs font-black text-white"><Send size={13}/> Add comment</button><div className="mt-6 space-y-3">{comments.map(c => <div key={c.id} className={`rounded-2xl border p-4 ${c.resolved ? 'opacity-60' : ''}`}><div className="flex items-center gap-2"><Avatar text={c.name === 'You' ? 'IB' : c.name.split(' ').map(x => x[0]).join('')}/><div className="text-xs font-black">{c.name}</div><span className="text-[10px] text-slate-400">{c.time}</span>{c.resolved ? <span className="ml-auto rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-black text-emerald-700">Resolved</span> : <button onClick={() => setComments(list => list.map(x => x.id === c.id ? { ...x, resolved: true } : x))} className="ml-auto text-[10px] font-black text-blue-600">Resolve</button>}</div><p className="mt-3 text-sm leading-6 text-slate-600">{c.text}</p></div>)}</div></div><div className="rounded-3xl border bg-slate-950 p-6 text-white"><div className="text-xs font-black uppercase tracking-widest text-blue-300">Review workflow</div><div className="mt-5 space-y-4">{[['Author', 'You', 'Complete'], ['Content reviewer', 'Maya Chen', 'Approved'], ['Learning designer', 'Omar Hassan', 'In review'], ['Release owner', 'You', 'Pending']].map(([role, name, status], i) => <div key={role} className="flex items-center gap-3"><div className="grid h-9 w-9 place-items-center rounded-full bg-white/10 text-xs font-black">{i + 1}</div><div className="min-w-0 flex-1"><div className="text-xs font-bold">{role}</div><div className="text-[10px] text-slate-500">{name}</div></div><span className="rounded-full bg-white/10 px-2 py-1 text-[9px] font-black">{status}</span></div>)}</div><button onClick={() => setReview(v => !v)} className="mt-7 flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 text-xs font-black text-slate-950">{review ? 'Review started' : 'Request review'} <ChevronRight size={14}/></button></div></section>; }
function Avatar({ text }: {
    text: string;
}) { return <div className="grid h-8 w-8 place-items-center rounded-full border-2 border-white bg-slate-900 text-[9px] font-black text-white">{text.slice(0, 2)}</div>; }

