'use client';
import { ChevronRight, GraduationCap, Play, RotateCcw } from 'lucide-react';
import { useState } from 'react';
import { motion } from 'framer-motion';
import { blockRegistry } from '@/lib/blocks';
import type { Block, ModuleDocument } from '@/lib/types';
import { StyledPreviewBlock } from '@/components/preview';
export function LearnerPortal({ doc }: {
    doc: ModuleDocument;
}) {
    const [started, setStarted] = useState(false);
    const [completed, setCompleted] = useState(false);
    const [active, setActive] = useState(0);
    const blocks = doc.blocks.filter(b => b.settings.isVisible);
    const progress = Math.round(((active + 1) / Math.max(1, blocks.length)) * 100);
    return <section className="mt-5 overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="border-b bg-white p-5 md:p-7"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><div className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[.18em] text-blue-600"><GraduationCap size={13}/> Learner experience</div><h2 className="mt-2 text-2xl font-black md:text-3xl">{doc.title}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">{doc.description || 'An interactive learning experience designed in EduForge.'}</p></div><div className="rounded-2xl bg-slate-50 p-4 text-center"><div className="text-2xl font-black">{doc.metadata.estimatedDuration}m</div><div className="text-[10px] font-bold uppercase tracking-widest text-slate-400">estimated</div></div></div><div className="mt-6 h-2 overflow-hidden rounded-full bg-slate-100"><motion.div animate={{ width: `${started ? progress : 0}%` }} className="h-full rounded-full bg-blue-600"/></div></div>
 <div className="grid min-h-[420px] lg:grid-cols-[220px_1fr]">
  <aside className="border-b bg-slate-50 p-4 lg:border-b-0 lg:border-r"><div className="text-[10px] font-black uppercase tracking-widest text-slate-400">Course map</div><div className="mt-3 space-y-1">{blocks.map((b, i) => <button key={b.id} onClick={() => { setStarted(true); setActive(i); }} className={`flex w-full items-center gap-2 rounded-xl p-2.5 text-left text-xs font-bold ${active === i ? 'bg-white text-blue-700 shadow-sm' : 'text-slate-500 hover:bg-white'}`}><span className="grid h-6 w-6 place-items-center rounded-lg bg-slate-100 text-[10px]">{i + 1}</span><span className="truncate">{blockRegistry.find(x => x.type === b.type)?.name || b.type}</span></button>)}</div></aside>
  <div className="p-5 md:p-8">{!started ? <div className="grid h-full min-h-[350px] place-items-center text-center"><div className="max-w-md"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-blue-50 text-blue-600"><Play size={25} fill="currentColor"/></div><h3 className="mt-5 text-2xl font-black">Ready to learn?</h3><p className="mt-2 text-sm leading-6 text-slate-500">Enter the learner portal to experience progress, interactive activities, knowledge checks and completion feedback.</p><button onClick={() => setStarted(true)} className="mt-6 rounded-2xl bg-blue-600 px-6 py-3 text-sm font-black text-white shadow-lg shadow-blue-200">Start learning</button></div></div> : completed ? <div className="grid min-h-[350px] place-items-center text-center"><div><div className="text-6xl">🏆</div><h3 className="mt-5 text-3xl font-black">Module completed</h3><p className="mt-2 text-sm text-slate-500">You finished every learning moment in this release.</p><div className="mt-5 flex justify-center gap-2"><span className="rounded-full bg-emerald-50 px-4 py-2 text-xs font-black text-emerald-700">100% complete</span><span className="rounded-full bg-amber-50 px-4 py-2 text-xs font-black text-amber-700">Certificate ready</span></div><button onClick={() => { setCompleted(false); setActive(0); }} className="mt-6 inline-flex items-center gap-2 rounded-xl border px-4 py-2 text-xs font-bold"><RotateCcw size={14}/> Restart</button></div></div> : <div><div className="flex items-center justify-between"><div><div className="text-[10px] font-black uppercase tracking-widest text-blue-600">Learning moment {active + 1}</div><h3 className="mt-2 text-xl font-black">{blockRegistry.find(x => x.type === blocks[active]?.type)?.name || 'Activity'}</h3></div><span className="text-xs font-black text-slate-400">{progress}%</span></div><div className="mt-6 rounded-2xl border border-dashed border-slate-200 bg-slate-50 p-6"><StyledPreviewBlock block={blocks[active]}/></div><div className="mt-6 flex justify-between"><button onClick={() => setActive(i => Math.max(0, i - 1))} disabled={active === 0} className="rounded-xl border px-4 py-2 text-xs font-bold disabled:opacity-30">Previous</button>{active === blocks.length - 1 ? <button onClick={() => setCompleted(true)} className="rounded-xl bg-slate-950 px-5 py-2.5 text-xs font-black text-white">Complete module</button> : <button onClick={() => setActive(i => Math.min(blocks.length - 1, i + 1))} className="inline-flex items-center gap-2 rounded-xl bg-blue-600 px-5 py-2.5 text-xs font-black text-white">Continue <ChevronRight size={14}/></button>}</div></div>}</div>
 </div></section>;
}

