'use client';
import type { Block } from '@/lib/types';
import { useModuleStore } from '@/store/module-store';
import { num, str } from './helpers';
export function QuizEditor({ block }: {
    block: Block;
}) { const update = useModuleStore(s => s.updateContent); const c = block.content; const options = Array.isArray(c.options) ? c.options as Record<string, unknown>[] : []; const set = (p: Record<string, unknown>) => update(block.id, { ...c, ...p }, 'Edit quiz'); return <div className="grid gap-2"><textarea aria-label="Quiz question" className="input" value={str(c.question)} onChange={e => set({ question: e.target.value })}/><label><input type="checkbox" checked={Boolean(c.allowMultiple)} onChange={e => set({ allowMultiple: e.target.checked })}/> Allow multiple correct answers</label>{options.map((o, i) => <div className="rounded border p-2" key={i}><div className="flex gap-2"><input className="input flex-1" value={str(o.text)} onChange={e => { const next = [...options]; next[i] = { ...o, text: e.target.value }; set({ options: next }); }}/><label><input type="checkbox" checked={Boolean(o.isCorrect)} onChange={e => { const next = [...options]; next[i] = { ...o, isCorrect: e.target.checked }; if (!Boolean(c.allowMultiple) && e.target.checked)
    next.forEach((v, n) => { if (n !== i)
        next[n] = { ...v, isCorrect: false }; }); set({ options: next }); }}/> Correct</label><button className="btn" onClick={() => set({ options: options.filter((_, n) => n !== i) })}>×</button></div><textarea className="input mt-2" placeholder="Explanation for this option" value={str(o.explanation)} onChange={e => { const next = [...options]; next[i] = { ...o, explanation: e.target.value }; set({ options: next }); }}/></div>)}<button className="btn" onClick={() => set({ options: [...options, { text: 'New option', isCorrect: false, explanation: '' }] })} disabled={options.length >= 6}>Add option</button><textarea className="input" placeholder="Overall explanation" value={str(c.overallExplanation)} onChange={e => set({ overallExplanation: e.target.value })}/><label>Points<input className="input" type="number" min={1} value={num(c.points, 10)} onChange={e => set({ points: Number(e.target.value) })}/></label><label>Timer (seconds, 0 = off)<input className="input" type="number" min={0} value={num(c.timeLimitSeconds, 0)} onChange={e => set({ timeLimitSeconds: Number(e.target.value) })}/></label><label>Attempt limit<input className="input" type="number" min={1} value={num(c.attemptLimit, 1)} onChange={e => set({ attemptLimit: Number(e.target.value) })}/></label></div>; }
export function TrueFalseEditor({ block }: {
    block: Block;
}) { const update = useModuleStore(s => s.updateContent); const c = block.content; const set = (p: Record<string, unknown>) => update(block.id, { ...c, ...p }, 'Edit true false'); return <div className="grid gap-3"><textarea aria-label="True false question" className="input" value={str(c.question)} onChange={e => set({ question: e.target.value })}/><select aria-label="Correct answer" className="input" value={String(Boolean(c.correct))} onChange={e => set({ correct: e.target.value === 'true' })}><option value="true">True</option><option value="false">False</option></select><textarea aria-label="Explanation" className="input" value={str(c.explanation)} onChange={e => set({ explanation: e.target.value })}/><label>Points<input className="input" type="number" min={1} value={num(c.points, 10)} onChange={e => set({ points: Number(e.target.value) })}/></label><label>Timer seconds<input className="input" type="number" min={0} value={num(c.timeLimitSeconds, 0)} onChange={e => set({ timeLimitSeconds: Number(e.target.value) })}/></label></div>; }
export function KnowledgeCheckEditor({ content: c, set }: {
    content: Record<string, unknown>;
    set: (p: Record<string, unknown>) => void;
}) { const options = Array.isArray(c.options) ? c.options as string[] : []; return <div className="grid gap-3"><textarea className="input" value={str(c.question)} onChange={e => set({ question: e.target.value })}/>{options.map((o, i) => <div key={i} className="flex gap-2"><input className="input" value={o} onChange={e => { const n = [...options]; n[i] = e.target.value; set({ options: n }); }}/><button className="btn" onClick={() => set({ options: options.filter((_, n) => n !== i) })}>×</button></div>)}<select className="input" value={Number(c.correctIndex) || 0} onChange={e => set({ correctIndex: Number(e.target.value) })}>{options.map((o, i) => <option value={i} key={i}>Best answer: {o}</option>)}</select><textarea className="input" placeholder="Feedback" value={str(c.explanation)} onChange={e => set({ explanation: e.target.value })}/><button className="btn" onClick={() => set({ options: [...options, 'New confidence level'] })}>Add option</button></div>; }

