'use client';
import { str } from './helpers';
export function ExplainerEditor({ content: c, set }: {
    content: Record<string, unknown>;
    set: (p: Record<string, unknown>) => void;
}) { const steps = Array.isArray(c.steps) ? c.steps as Record<string, unknown>[] : []; return <div className="grid gap-2"><input aria-label="Explainer title" className="input" value={str(c.title)} onChange={e => set({ title: e.target.value })}/>{steps.map((step, i) => <div key={i} className="rounded border p-2"><input className="input mb-2" value={str(step.title)} onChange={e => { const next = [...steps]; next[i] = { ...step, title: e.target.value }; set({ steps: next }); }}/><textarea className="input" value={str(step.description)} onChange={e => { const next = [...steps]; next[i] = { ...step, description: e.target.value }; set({ steps: next }); }}/></div>)}<div className="flex gap-2"><button className="btn" disabled={steps.length >= 10} onClick={() => set({ steps: [...steps, { title: 'New step', description: 'Explain this step.' }] })}>Add step</button><button className="btn" disabled={steps.length <= 3} onClick={() => set({ steps: steps.slice(0, -1) })}>Remove last</button></div><label><input type="checkbox" checked={Boolean(c.autoPlay)} onChange={e => set({ autoPlay: e.target.checked })}/> Auto-play</label></div>; }
export function ScenarioEditor({ content: c, set }: {
    content: Record<string, unknown>;
    set: (p: Record<string, unknown>) => void;
}) { const options = Array.isArray(c.options) ? c.options as Record<string, unknown>[] : []; return <div className="grid gap-3"><input className="input" aria-label="Scenario title" value={str(c.title)} onChange={e => set({ title: e.target.value })}/><textarea className="input min-h-24" aria-label="Scenario context" value={str(c.context)} onChange={e => set({ context: e.target.value })}/>{options.map((o, i) => <div key={i} className="rounded-2xl border p-3"><div className="flex gap-2"><input className="input" value={str(o.label)} onChange={e => { const n = [...options]; n[i] = { ...o, label: e.target.value }; set({ options: n }); }}/><input className="input w-24" type="number" value={Number(o.score) || 0} onChange={e => { const n = [...options]; n[i] = { ...o, score: Number(e.target.value) }; set({ options: n }); }}/></div><textarea className="input mt-2" value={str(o.feedback)} onChange={e => { const n = [...options]; n[i] = { ...o, feedback: e.target.value }; set({ options: n }); }}/></div>)}<button className="btn" disabled={options.length >= 5} onClick={() => set({ options: [...options, { label: 'New decision', feedback: 'Explain the consequence.', score: 5 }] })}>Add decision</button></div>; }
export function FlashcardsEditor({ content: c, set }: {
    content: Record<string, unknown>;
    set: (p: Record<string, unknown>) => void;
}) { const cards = Array.isArray(c.cards) ? c.cards as Record<string, unknown>[] : []; return <div className="grid gap-3"><input className="input" value={str(c.title)} onChange={e => set({ title: e.target.value })}/>{cards.map((card, i) => <div key={i} className="grid gap-2 rounded-2xl border p-3 sm:grid-cols-2"><input className="input" placeholder="Front" value={str(card.front)} onChange={e => { const n = [...cards]; n[i] = { ...card, front: e.target.value }; set({ cards: n }); }}/><textarea className="input" placeholder="Back" value={str(card.back)} onChange={e => { const n = [...cards]; n[i] = { ...card, back: e.target.value }; set({ cards: n }); }}/></div>)}<button className="btn" disabled={cards.length >= 20} onClick={() => set({ cards: [...cards, { front: 'New term', back: 'Explain the concept.' }] })}>Add flashcard</button></div>; }

