'use client';
import { str, num } from './helpers';
export function AccordionEditor({ content: c, set }: {
    content: Record<string, unknown>;
    set: (p: Record<string, unknown>) => void;
}) { const items = Array.isArray(c.items) ? c.items as Record<string, unknown>[] : []; return <div className="grid gap-2">{items.map((x, i) => <div className="rounded border p-2" key={i}><div className="flex gap-2"><input aria-label={`Accordion ${i + 1} title`} className="input mb-2 flex-1" value={str(x.title)} onChange={e => { const next = [...items]; next[i] = { ...x, title: e.target.value }; set({ items: next }); }}/><button className="btn" onClick={() => set({ items: items.filter((_, n) => n !== i) })}>Remove</button></div><textarea className="input" value={str(x.body)} onChange={e => { const next = [...items]; next[i] = { ...x, body: e.target.value }; set({ items: next }); }}/></div>)}<button className="btn" onClick={() => set({ items: [...items, { title: 'New question', body: 'Answer' }] })}>Add FAQ item</button>{items.length >= 20 ? <p className="text-xs text-amber-700">20+ items can be hard to scan; consider splitting this accordion.</p> : null}</div>; }
export function ProgressEditor({ content: c, set }: {
    content: Record<string, unknown>;
    set: (p: Record<string, unknown>) => void;
}) { const total = num(c.total, 5); const labels = Array.isArray(c.labels) ? c.labels as string[] : []; return <div className="grid gap-3"><label>Display<select className="input" value={str(c.mode, 'linear')} onChange={e => set({ mode: e.target.value })}><option value="linear">Linear</option><option value="branching">Branching</option></select></label><label>Total steps<input className="input" type="number" min={2} value={total} onChange={e => set({ total: Number(e.target.value) })}/></label><label>Current step<input className="input" type="number" min={1} max={total} value={num(c.current, 1)} onChange={e => set({ current: Number(e.target.value) })}/></label><div>{Array.from({ length: total }, (_, i) => <input key={i} aria-label={`Step ${i + 1} label`} className="input mb-1" value={labels[i] ?? `Step ${i + 1}`} onChange={e => { const next = Array.from({ length: total }, (_, n) => labels[n] ?? `Step ${n + 1}`); next[i] = e.target.value; set({ labels: next }); }}/>)}</div></div>; }
const financialIcons = ['🏦', '💰', '📈', '📉', '🪙', '💳', '🏠', '🎯', '🧾', '📊', '💵', '🔒', '🎓', '🛡️', '⏳', '🌱', '🚀', '🏆', '🤝', '📚', '🏖️', '💎'];
export function BadgeEditor({ content: c, set }: {
    content: Record<string, unknown>;
    set: (p: Record<string, unknown>) => void;
}) { return <div className="grid gap-3"><label>Icon<select className="input" value={str(c.icon, '🏆')} onChange={e => set({ icon: e.target.value })}>{financialIcons.map(x => <option key={x}>{x}</option>)}</select></label><input aria-label="Badge title" className="input" value={str(c.title)} onChange={e => set({ title: e.target.value })}/><textarea aria-label="Badge description" className="input" value={str(c.description)} onChange={e => set({ description: e.target.value })}/><input aria-label="Unlock condition" className="input" placeholder="Unlock condition" value={str(c.unlockCondition)} onChange={e => set({ unlockCondition: e.target.value })}/><label><input type="checkbox" checked={Boolean(c.unlocked)} onChange={e => set({ unlocked: e.target.checked })}/> Unlocked</label></div>; }

