'use client';
import { useState } from 'react';
import { Download } from 'lucide-react';
import { amortization, calculateCompound, calculateSIP, compoundGrowth, emiSummary, formatINR, sipYears } from '@/lib/finance';
import { Card, CalcInput, Metric, Donut, LineChart, downloadCsv } from './shared';
export function EMICalculator({ content: c }: {
    content: Record<string, unknown>;
}) { const [principal, setPrincipal] = useState(Number(c.principal) || 500000), [rate, setRate] = useState(Number(c.annualRate) || 8.5), [months, setMonths] = useState(Number(c.months) || 240), [showAll, setShowAll] = useState(false); const summary = emiSummary(principal, rate, months), rows = amortization(principal, rate, months); return <Card title="EMI Calculator"><div className="grid gap-3 sm:grid-cols-3"><CalcInput label="Principal" value={principal} min={10000} max={100000000} onChange={setPrincipal}/><CalcInput label="Rate %" value={rate} min={0} max={36} step={0.1} onChange={setRate}/><CalcInput label="Tenure months" value={months} min={1} max={360} onChange={setMonths}/></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Monthly EMI" value={formatINR(summary.emi)}/><Metric label="Total Interest" value={formatINR(summary.totalInterest)}/><Metric label="Total Payment" value={formatINR(summary.totalPayment)}/></div><Donut primary={principal} secondary={summary.totalInterest}/><div className="mt-4 flex justify-between"><strong>Amortisation schedule</strong><div className="flex gap-2"><button className="btn" onClick={() => setShowAll(v => !v)}>{showAll ? 'Show first 12' : 'Show all'}</button><button className="btn" onClick={() => downloadCsv('emi-amortisation.csv', rows.map(r => ({ Month: r.month, 'Opening Balance': r.openingBalance, EMI: r.emi, Principal: r.principal, Interest: r.interest, 'Closing Balance': r.closingBalance })))}><Download size={14}/> CSV</button></div></div><div className="mt-2 max-h-[400px] overflow-auto"><table className="w-full text-xs"><thead><tr><th>Month</th><th>Opening</th><th>EMI</th><th>Principal</th><th>Interest</th><th>Closing</th></tr></thead><tbody>{rows.slice(0, showAll ? rows.length : 12).map(r => <tr key={r.month} className="border-t"><td>{r.month}</td><td>{formatINR(r.openingBalance)}</td><td>{formatINR(r.emi)}</td><td>{formatINR(r.principal)}</td><td>{formatINR(r.interest)}</td><td>{formatINR(r.closingBalance)}</td></tr>)}</tbody></table></div>{rate === 0 ? <p className="mt-2 text-xs">0% rate: EMI = Principal / Tenure.</p> : null}</Card>; }
export function SIPCalculator({ content: c }: {
    content: Record<string, unknown>;
}) { const [monthly, setMonthly] = useState(Number(c.monthly) || 5000), [rate, setRate] = useState(Number(c.annualRate) || 12), [years, setYears] = useState(Number(c.years) || 10); const fv = calculateSIP(monthly, rate, years), invested = monthly * years * 12, gain = fv - invested, rows = sipYears(monthly, rate, years); return <Card title="SIP Calculator"><div className="grid gap-3 sm:grid-cols-3"><CalcInput label="Monthly investment" value={monthly} min={500} max={1000000} onChange={setMonthly}/><CalcInput label="Expected return %" value={rate} min={1} max={30} step={0.5} onChange={setRate}/><CalcInput label="Duration years" value={years} min={1} max={40} onChange={setYears}/></div><div className="mt-4 grid gap-3 sm:grid-cols-3"><Metric label="Future Value" value={formatINR(fv)}/><Metric label="Total Invested" value={formatINR(invested)}/><Metric label="Wealth Gained" value={formatINR(gain)}/></div><Donut primary={invested} secondary={gain}/><div className="mt-4 flex justify-between"><strong>Year-by-year growth</strong><button className="btn" onClick={() => downloadCsv('sip-growth.csv', rows.map(r => ({ Year: r.year, Invested: r.invested, 'Future Value': r.futureValue, 'Wealth Gained': r.wealthGained })))}><Download size={14}/> CSV</button></div><table className="mt-2 w-full text-xs"><thead><tr><th>Year</th><th>Invested</th><th>Future Value</th><th>Wealth Gained</th></tr></thead><tbody>{rows.map(r => <tr className="border-t" key={r.year}><td>{r.year}</td><td>{formatINR(r.invested)}</td><td>{formatINR(r.futureValue)}</td><td>{formatINR(r.wealthGained)}</td></tr>)}</tbody></table></Card>; }
export function CompoundCalculator({ content: c }: {
    content: Record<string, unknown>;
}) { const [principal, setPrincipal] = useState(Number(c.principal) || 100000), [rate, setRate] = useState(Number(c.annualRate) || 8), [years, setYears] = useState(Number(c.years) || 10), [frequency, setFrequency] = useState(Number(c.frequency) || 12); const fv = calculateCompound(principal, rate, years, frequency), rows = compoundGrowth(principal, rate, years, frequency); return <Card title="Compound Interest"><div className="grid gap-3 sm:grid-cols-4"><CalcInput label="Principal" value={principal} min={1} max={100000000} onChange={setPrincipal}/><CalcInput label="Rate %" value={rate} min={0} max={100} step={0.1} onChange={setRate}/><CalcInput label="Years" value={years} min={1} max={100} onChange={setYears}/><label>Compounding<select className="input" value={frequency} onChange={e => setFrequency(Number(e.target.value))}>{[[12, 'Monthly'], [4, 'Quarterly'], [2, 'Half-yearly'], [1, 'Annually']].map(([v, l]) => <option key={String(v)} value={v}>{String(l)}</option>)}</select></label></div><Metric label="Maturity value" value={formatINR(fv)}/><LineChart rows={rows}/><table className="mt-4 w-full text-xs"><thead><tr><th>Year</th><th>Value</th></tr></thead><tbody>{rows.map(r => <tr className="border-t" key={r.year}><td>{r.year}</td><td>{formatINR(r.value)}</td></tr>)}</tbody></table></Card>; }

