'use client';
import { useEffect, useState } from 'react';
import { Check, Copy, Play, X } from 'lucide-react';
import { parseVideoUrl } from '@/lib/video';
import type { Block } from '@/lib/types';
import { Card } from './shared';
export function VideoPreview({ content }: {
    content: Record<string, unknown>;
}) { const parsed = parseVideoUrl(String(content.url ?? '')); const [play, setPlay] = useState(false); if (!parsed)
    return <div role="alert" className="rounded border border-red-200 bg-red-50 p-4 text-red-700">Only YouTube and Vimeo URLs are supported.</div>; return <div className="overflow-hidden rounded-xl border bg-black"><div className="relative aspect-video">{play ? <iframe className="absolute inset-0 h-full w-full" src={parsed.embedUrl} title={String(content.title ?? 'Video lesson')} allow="autoplay; encrypted-media" allowFullScreen/> : <><div className="grid h-full place-items-center text-white">{parsed.thumbnailUrl ? <img src={parsed.thumbnailUrl} alt="Video thumbnail" className="absolute inset-0 h-full w-full object-cover opacity-80"/> : null}<Play /></div><button onClick={() => setPlay(true)} className="absolute inset-0" aria-label="Play video"/></>}</div></div>; }
export function MCQ({ block }: {
    block: Block;
}) { const c = block.content, opts = Array.isArray(c.options) ? c.options as Record<string, unknown>[] : [], multi = Boolean(c.allowMultiple); const [selected, setSelected] = useState<number[]>([]), [submitted, setSubmitted] = useState(false), [seconds, setSeconds] = useState(Number(c.timeLimitSeconds) || 0); useEffect(() => { if (!submitted && seconds > 0) {
    const id = setInterval(() => setSeconds(v => Math.max(0, v - 1)), 1000);
    return () => clearInterval(id);
} }, [submitted, seconds]); useEffect(() => { if (seconds === 0 && Number(c.timeLimitSeconds) > 0)
    setSubmitted(true); }, [seconds, c.timeLimitSeconds]); const toggle = (i: number) => setSelected(v => multi ? (v.includes(i) ? v.filter(x => x !== i) : [...v, i]) : [i]); const correct = opts.every((o, i) => Boolean(o.isCorrect) === selected.includes(i)); return <Card title="Knowledge Check"><p className="mb-3 font-semibold">{String(c.question)}</p>{Number(c.timeLimitSeconds) > 0 ? <p className="text-sm">Time remaining: {seconds}s</p> : null}<div role={multi ? 'group' : 'radiogroup'} aria-label="Quiz options">{opts.map((o, i) => <button key={i} role={multi ? 'checkbox' : 'radio'} aria-checked={selected.includes(i)} disabled={submitted} onClick={() => toggle(i)} className={`mb-2 block w-full rounded-lg border p-3 text-left ${selected.includes(i) ? 'border-blue-500 bg-blue-50' : ''}`}>{String(o.text)}</button>)}</div><button className="btn" disabled={!selected.length || submitted} onClick={() => setSubmitted(true)}>Submit answer</button>{submitted ? <div className="mt-3">{correct ? <p><Check className="inline text-green-600"/> Correct • +{Number(c.points) || 0} points</p> : <p><X className="inline text-red-600"/> Review the explanations</p>}{selected.map(i => opts[i]?.explanation ? <p key={i} className="text-sm">{String(opts[i].explanation)}</p> : null)}{c.overallExplanation ? <p className="mt-2 text-sm">{String(c.overallExplanation)}</p> : null}</div> : null}</Card>; }
export function TrueFalse({ block }: {
    block: Block;
}) { const c = block.content; const limit = Math.max(1, Number(c.attemptLimit) || 1); const [answer, setAnswer] = useState<boolean | null>(null), [submitted, setSubmitted] = useState(false), [attempts, setAttempts] = useState(0), [seconds, setSeconds] = useState(Number(c.timeLimitSeconds) || 0); useEffect(() => { if (!submitted && seconds > 0) {
    const id = setInterval(() => setSeconds(v => Math.max(0, v - 1)), 1000);
    return () => clearInterval(id);
} }, [submitted, seconds]); useEffect(() => { if (seconds === 0 && Number(c.timeLimitSeconds) > 0)
    setSubmitted(true); }, [seconds, c.timeLimitSeconds]); const submit = () => { setAttempts(v => v + 1); setSubmitted(true); }; return <Card title="True or False"><p className="mb-3 font-semibold">{String(c.question)}</p>{Number(c.timeLimitSeconds) > 0 ? <p className="text-sm">Time remaining: {seconds}s</p> : null}<div role="radiogroup" className="flex gap-2"><button role="radio" aria-checked={answer === true} className="btn" disabled={submitted || attempts >= limit} onClick={() => setAnswer(true)}>True</button><button role="radio" aria-checked={answer === false} className="btn" disabled={submitted || attempts >= limit} onClick={() => setAnswer(false)}>False</button></div><button className="btn mt-2" disabled={answer === null || submitted || attempts >= limit} onClick={submit}>Submit</button>{submitted ? <div className="mt-3"><p>{answer === Boolean(c.correct) ? 'Correct! ' : 'Not quite. '}{String(c.explanation)}</p>{answer !== Boolean(c.correct) && attempts < limit ? <button className="btn mt-2" onClick={() => { setSubmitted(false); setAnswer(null); }}>Try again ({limit - attempts} left)</button> : null}</div> : null}</Card>; }
export function ScenarioPreview({ content: c }: {
    content: Record<string, unknown>;
}) { const opts = Array.isArray(c.options) ? c.options as Record<string, unknown>[] : []; const [choice, setChoice] = useState<number | null>(null); return <Card title={String(c.title || 'Scenario')}><p className="mb-4 opacity-80">{String(c.context || '')}</p><div className="grid gap-2">{opts.map((o, i) => <button key={i} onClick={() => setChoice(i)} className={`rounded-xl border p-4 text-left transition ${choice === i ? 'border-blue-500 bg-blue-50' : ''}`}><div className="font-semibold">{String(o.label)}</div>{choice === i ? <p className="mt-2 text-sm opacity-75">{String(o.feedback)}</p> : null}</button>)}</div>{choice !== null ? <div className="mt-4 rounded-xl bg-slate-50 p-3 text-xs font-bold">Decision impact: +{Number(opts[choice]?.score) || 0} points</div> : null}</Card>; }
export function FlashcardsPreview({ content: c }: {
    content: Record<string, unknown>;
}) { const cards = Array.isArray(c.cards) ? c.cards as Record<string, unknown>[] : []; const [index, setIndex] = useState(0); const [flipped, setFlipped] = useState(false); const card = cards[index]; return <Card title={String(c.title || 'Flashcards')}><button onClick={() => setFlipped(v => !v)} className="min-h-40 w-full rounded-2xl border-2 border-dashed bg-slate-50 p-6 text-center transition hover:border-blue-400"><div className="text-[10px] font-black uppercase tracking-widest text-blue-600">{flipped ? 'Answer' : 'Recall'}</div><div className="mt-4 text-xl font-black">{String(flipped ? card?.back : card?.front || '')}</div><div className="mt-3 text-xs text-slate-400">Click to flip</div></button><div className="mt-3 flex items-center justify-between"><button className="btn" disabled={index === 0} onClick={() => { setIndex(i => Math.max(0, i - 1)); setFlipped(false); }}>Previous</button><span className="text-xs font-bold text-slate-400">{index + 1} / {cards.length}</span><button className="btn" disabled={index === cards.length - 1} onClick={() => { setIndex(i => Math.min(cards.length - 1, i + 1)); setFlipped(false); }}>Next</button></div></Card>; }
export function KnowledgeCheckPreview({ content: c }: {
    content: Record<string, unknown>;
}) { const options = Array.isArray(c.options) ? c.options as string[] : []; const [answer, setAnswer] = useState<number | null>(null); const [submitted, setSubmitted] = useState(false); return <Card title="Knowledge Check"><p className="mb-4 font-bold">{String(c.question || '')}</p><div className="grid gap-2">{options.map((o, i) => <button key={i} onClick={() => setAnswer(i)} className={`rounded-xl border p-3 text-left ${answer === i ? 'border-blue-500 bg-blue-50' : ''}`}>{o}</button>)}</div><button className="btn mt-3" disabled={answer === null} onClick={() => setSubmitted(true)}>Check confidence</button>{submitted ? <p className={`mt-3 rounded-xl p-3 text-sm font-semibold ${answer === Number(c.correctIndex) ? 'bg-emerald-50 text-emerald-800' : 'bg-amber-50 text-amber-800'}`}>{answer === Number(c.correctIndex) ? 'Great choice. ' : 'Consider another review pass. '}{String(c.explanation || '')}</p> : null}</Card>; }

